### ISSUE TITLE
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' 

### ISSUE THREAD

**Issue by dorost1234** [cindyxinyiwang/emea#3]
Hi
I am getting this error when running the codes for 
```
bash job_scripts/test_panx_adapter_emea_s1.sh
```
I appreciate your help
thanks 

```
PyTorch version 1.8.0 available.
Traceback (most recent call last):
  File "third_party/run_tag.py", line 39, in <module>
    from utils_tag import convert_examples_to_features
  File "/user/dara/codes/temp/emea/third_party/utils_tag.py", line 24, in <module>
    from transformers import XLMTokenizer
  File /user/dara/codes/temp/emea/src/transformers/__init__.py", line 675, in <module>
    from .trainer import Trainer
  File "/user/dara/codes/temp/emea/src/transformers/trainer.py", line 69, in <module>
    from .trainer_pt_utils import (
  File "/user/dara/codes/temp/emea/src/transformers/trainer_pt_utils.py", line 40, in <module>
    from torch.optim.lr_scheduler import SAVE_STATE_WARNING
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/user/dara/libs/anaconda3/envs/test/lib/python3.7/site-packages/torch/optim/lr_scheduler.py)
```

**Comment by dorost1234** [comment]
solved with installing torch 1.4
