### ISSUE TITLE
Cannot run evaluation function (gradients are None)

### ISSUE THREAD

**Issue by msclar** [cindyxinyiwang/emea#5]
Hi! I am trying to run the train script `bash job_scripts/train_panx_adapter.sh` without changing anything from the repo but the code is crashing in `calc_weight_multi`, during evaluation. First, it crashed with a torch warning (see first snippet below), but I set `allow_unused=True` in case this warning only appeared in later versions of pytorch (though I am using 1.4.0 right now).

Even after adding `allow_unused=True`, the code crashes because all gradients are None. 

**Traceback using code as-is:**

```
Evaluating:   0%|                                                                                                                                                            | 0/313 [00:00<?, ?it/s]
Iteration:  60%|██████████████████████████████████████████████████████████████████████████████████████▊                                                          | 1499/2503 [01:11<00:47, 20.93it/s]
Epoch:   1%|█▌                                                                                                                                                    | 1/100 [03:09<5:12:19, 189.28s/it]
Traceback (most recent call last):
  File "third_party/run_tag.py", line 913, in <module>
    main()
  File "third_party/run_tag.py", line 715, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer, labels, pad_token_label_id, lang_adapter_names, task_name, lang2id)
  File "third_party/run_tag.py", line 186, in train
    result, _ = evaluate(args, model, tokenizer, labels, pad_token_label_id, mode="dev", prefix=global_step, lang=args.train_langs, lang2id=lang2id, lang_adapter_names=lang_adapter_names, task_name=task_name)
  File "third_party/run_tag.py", line 301, in evaluate
    adapter_weight = calc_weight_multi(args, model, batch, lang_adapter_names, task_name, adapter_weight, calc_weight_step)
  File "third_party/run_tag.py", line 264, in calc_weight_multi
    grads = torch.autograd.grad(entropy, adapter_weights)
  File "/gscratch/xlab/msclar/anaconda3/envs/adapterenv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 155, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.
```

**Traceback after adding `torch.autograd.grad(entropy, adapter_weights, allow_unused=True)`, with printed variables:**

```
step 0
third_party/run_tag.py:254: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.13 [00:00<?, ?it/s]
  normed_adapter_weights = [torch.nn.functional.softmax(w) for w in adapter_weights]
entropy tensor(1.0772, device='cuda:0', grad_fn=<DivBackward0>)
adapter_weights [tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True), tensor([0.5000], device='cuda:0', requires_grad=True)]
grads (None, None, None, None, None, None, None, None, None, None, None, None, None)
Evaluating:   0%|                                                                                                                              | 0/313 [00:00<?, ?it/s]
Iteration:  60%|████████████████████████████████████████████████████████████████████▊                                              | 1499/2503 [01:11<00:47, 20.95it/s]
Epoch:   1%|█▏                                                                                                                      | 1/100 [03:09<5:12:52, 189.62s/it]
Traceback (most recent call last):
  File "third_party/run_tag.py", line 914, in <module>
    main()
  File "third_party/run_tag.py", line 716, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer, labels, pad_token_label_id, lang_adapter_names, task_name, lang2id)
  File "third_party/run_tag.py", line 186, in train
    result, _ = evaluate(args, model, tokenizer, labels, pad_token_label_id, mode="dev", prefix=global_step, lang=args.train_langs, lang2id=lang2id, lang_adapter_names=lang_adapter_names, task_name=task_name)
  File "third_party/run_tag.py", line 302, in evaluate
    adapter_weight = calc_weight_multi(args, model, batch, lang_adapter_names, task_name, adapter_weight, calc_weight_step)
  File "third_party/run_tag.py", line 270, in calc_weight_multi
    adapter_weights[i] = adapter_weights[i].data - 10*grads[i].data
AttributeError: 'NoneType' object has no attribute 'data'
```

Do you know what may be happening? I only added print statements, but did not modify anything else from the codebase. For the adapter-transformers package, I cloned the repo on version 1.1.1, replaced everything from the `emea/src/transformers` dir, and did `pip install -e .`. 

Also, I don't understand the range(13) on [line 250](https://github.com/cindyxinyiwang/emea/blob/main/third_party/run_tag.py#L250). Is this to ensure always creating more than enough adapter weights?

Thanks a lot for your help!

**Comment by cindyxinyiwang** [comment]
Hi,

Sorry I didn't test the training script because I basically used the default adapter training method, and the method in our paper is mainly done at decoding time. I think for training you probably want to comment out the calc_weight_multi function, since you are probably just training a single adapter for your task/language, instead of using multiple adapters(which the calc_weight_multi helps by getting the ensemble weights).

The range(13) basically creates a weight for each bert layer. I hard-coded this for convenience - probably should write a comment for this. Hope it helps!

**Comment by msclar** [comment]
Thank you for the detailed response! It was super helpful to understand more, I ended up using another script to train and just load the adapters in `run_tag.py`. 

For some reason I am not able to get better than chance performance if I am using `roberta-base` instead of `bert-base-uncased`, but this is probably unrelated to EMEA's additions to the original run_tag.py code.

Thanks again!
